<?php
declare(strict_types=1);
namespace App\Entity\Production;
use App\Entity\Catalog\MeasurementUnit; use App\Entity\Common\Timestampable; use App\Entity\Inventory\InventoryLot; use App\Entity\Inventory\InventoryMovement; use App\Entity\Materials\MaterialVariant; use App\Entity\Orders\ServiceOrderItem; use App\Entity\Users\User; use App\Enum\Inventory\QuantitySource; use App\Enum\Production\CalculationMethod; use Doctrine\DBAL\Types\Types; use Doctrine\ORM\Mapping as ORM;
#[ORM\Entity,ORM\Table(name:'production_material_usages'),ORM\HasLifecycleCallbacks]
/** Compara el consumo planeado con la medición opcional y conserva el cálculo histórico. */
class ProductionMaterialUsage
{
 use Timestampable; /** Identificador interno del registro. */ #[ORM\Id,ORM\GeneratedValue,ORM\Column] private ?int $id=null; /** Partida de orden para la que se consume el material. */ #[ORM\ManyToOne] #[ORM\JoinColumn(name:'service_order_item_id',nullable:false,onDelete:'RESTRICT')] private ServiceOrderItem $serviceOrderItem;
 /** Presentación prevista o efectivamente utilizada. */ #[ORM\ManyToOne] #[ORM\JoinColumn(name:'material_variant_id',nullable:false,onDelete:'RESTRICT')] private MaterialVariant $variant; /** Lote físico consumido cuando aplica trazabilidad. */ #[ORM\ManyToOne] #[ORM\JoinColumn(name:'lot_id',onDelete:'RESTRICT')] private ?InventoryLot $lot=null;
 /** Unidad común para cantidades planeada, real, contabilizada y merma. */ #[ORM\ManyToOne] #[ORM\JoinColumn(name:'unit_id',nullable:false,onDelete:'RESTRICT')] private MeasurementUnit $unit; /** Movimiento definitivo que descontó el inventario. */ #[ORM\OneToOne] #[ORM\JoinColumn(name:'inventory_movement_id',onDelete:'RESTRICT')] private ?InventoryMovement $movement=null;
 /** Usuario que proporcionó o confirmó la medición. */ #[ORM\ManyToOne] #[ORM\JoinColumn(name:'measured_by',onDelete:'RESTRICT')] private ?User $measuredBy=null; /** Consumo calculado originalmente por la BOM. */ #[ORM\Column(name:'planned_quantity',type:Types::DECIMAL,precision:20,scale:6)] private string $plannedQuantity;
 /** Consumo real opcional; permanece NULL si producción no lo captura. */ #[ORM\Column(name:'actual_quantity',type:Types::DECIMAL,precision:20,scale:6,nullable:true)] private ?string $actualQuantity=null; /** Cantidad usada para inventario y costo: real si existe, planeada en caso contrario. */ #[ORM\Column(name:'posted_quantity',type:Types::DECIMAL,precision:20,scale:6)] private string $postedQuantity;
 /** Parte identificada como merma dentro del consumo real; no se suma nuevamente. */ #[ORM\Column(name:'waste_quantity',type:Types::DECIMAL,precision:20,scale:6,nullable:true)] private ?string $wasteQuantity=null; /** Procedencia de la cantidad contabilizada: estimada, medida, derivada o reportada por máquina. */ #[ORM\Column(name:'quantity_source',length:20,enumType:QuantitySource::class)] private QuantitySource $quantitySource=QuantitySource::ESTIMATED;
 /** Técnica utilizada para obtener el dato real. */ #[ORM\Column(name:'measurement_method',length:30,nullable:true)] private ?string $measurementMethod=null; /** Explicación opcional de una merma identificada. */ #[ORM\Column(name:'waste_reason',length:255,nullable:true)] private ?string $wasteReason=null;
 /** Algoritmo predefinido utilizado para calcular lo planeado. */ #[ORM\Column(name:'calculation_method',length:30,enumType:CalculationMethod::class)] private CalculationMethod $calculationMethod; /** Versión exacta de ese algoritmo. */ #[ORM\Column(name:'calculation_method_version')] private int $calculationMethodVersion;
 /** Fotografía de entradas, parámetros y resultado del cálculo original. */ #[ORM\Column(name:'calculation_snapshot',type:Types::JSON)] private array $calculationSnapshot; /** Instante UTC de la medición real, si existió. */ #[ORM\Column(name:'measured_at',type:Types::DATETIME_IMMUTABLE,nullable:true)] private ?\DateTimeImmutable $measuredAt=null;
 public function __construct(ServiceOrderItem $item,MaterialVariant $variant,MeasurementUnit $unit,string $planned,CalculationMethod $method,int $version,array $snapshot){$this->serviceOrderItem=$item;$this->variant=$variant;$this->unit=$unit;$this->plannedQuantity=$this->postedQuantity=$planned;$this->calculationMethod=$method;$this->calculationMethodVersion=$version;$this->calculationSnapshot=$snapshot;$this->initializeTimestamps();}
 public function recordActual(string $actual,?string $waste,QuantitySource $source,User $user,string $method):void{if($source===QuantitySource::ESTIMATED)throw new \InvalidArgumentException('Un consumo real no puede marcarse como estimado.');$this->actualQuantity=$this->postedQuantity=$actual;$this->wasteQuantity=$waste;$this->quantitySource=$source;$this->measuredBy=$user;$this->measurementMethod=$method;$this->measuredAt=new \DateTimeImmutable('now',new \DateTimeZone('UTC'));}
 public function getActualQuantity():?string{return $this->actualQuantity;} public function getPostedQuantity():string{return $this->postedQuantity;} public function getQuantitySource():QuantitySource{return $this->quantitySource;}
}
