<?php
declare(strict_types=1);
namespace App\Entity\Clients;
use App\Entity\Common\Address; use App\Repository\Clients\ClientAddressRepository; use Doctrine\ORM\Mapping as ORM;
/** Relaciona un cliente con un domicilio reutilizable y define su uso comercial. */
#[ORM\Entity(repositoryClass:ClientAddressRepository::class),ORM\Table(name:'client_addresses')]
#[ORM\Index(name:'idx_client_addresses_client_active',columns:['client_id','is_active']),ORM\Index(name:'idx_client_addresses_delivery_zone',columns:['delivery_zone_id'])]
#[ORM\UniqueConstraint(name:'uniq_client_address_default_type',columns:['default_client_type_key']),ORM\HasLifecycleCallbacks]
class ClientAddress {
    /** Identificador interno. */ #[ORM\Id,ORM\GeneratedValue,ORM\Column] private ?int $id=null;
    /** Cliente que utiliza el domicilio. */ #[ORM\ManyToOne(targetEntity:Client::class),ORM\JoinColumn(name:'client_id',nullable:false,onDelete:'RESTRICT')] private Client $client;
    /** Única fuente de calle, números, colonia, CP, ciudad y notas. */ #[ORM\ManyToOne(targetEntity:Address::class,cascade:['persist']),ORM\JoinColumn(name:'address_id',nullable:false,onDelete:'RESTRICT')] private Address $address;
    /** Etiqueta visible. */ #[ORM\Column(length:100)] private string $label;
    /** Persona que recibe. */ #[ORM\Column(name:'recipient_name',length:160,nullable:true)] private ?string $recipientName=null;
    /** Uso principal: FISCAL, COMMERCIAL o DELIVERY. */ #[ORM\Column(name:'address_type',length:20,options:['default'=>'COMMERCIAL'])] private string $addressType='COMMERCIAL';
    /** Zona logística. */ #[ORM\ManyToOne(targetEntity:DeliveryZone::class),ORM\JoinColumn(name:'delivery_zone_id',nullable:true,onDelete:'RESTRICT')] private ?DeliveryZone $deliveryZone=null;
    /** Costo pactado de entrega. */ #[ORM\Column(name:'delivery_cost',type:'decimal',precision:12,scale:2,options:['default'=>'0.00'])] private string $deliveryCost='0.00';
    /** Predeterminado para el tipo indicado. */ #[ORM\Column(name:'is_default',options:['default'=>false])] private bool $isDefault=false;
    #[ORM\Column(name:'default_client_type_key',length:64,nullable:true,insertable:false,updatable:false,generated:'ALWAYS',columnDefinition:"VARCHAR(64) GENERATED ALWAYS AS (CASE WHEN is_active = 1 AND is_default = 1 THEN CONCAT(client_id, ':', address_type) ELSE NULL END) STORED")] private ?string $defaultClientTypeKey=null;
    /** Vigencia de la relación. */ #[ORM\Column(name:'is_active',options:['default'=>true])] private bool $isActive=true;
    #[ORM\Column(name:'created_at',type:'datetime_immutable')] private \DateTimeImmutable $createdAt; #[ORM\Column(name:'updated_at',type:'datetime_immutable')] private \DateTimeImmutable $updatedAt;
    public function __construct(Client $client,Address $address){$this->client=$client;$this->address=$address;$this->createdAt=$this->updatedAt=new \DateTimeImmutable('now',new \DateTimeZone('UTC'));}
    public function getId():?int{return $this->id;} public function getClient():Client{return $this->client;} public function getAddress():Address{return $this->address;}
    public function getLabel():string{return $this->label;} public function setLabel(string $v):self{$this->label=trim($v);return $this;} public function getRecipientName():?string{return $this->recipientName;} public function setRecipientName(?string $v):self{$v=trim((string)$v);$this->recipientName=$v?:null;return $this;}
    public function getAddressType():string{return $this->addressType;} public function setAddressType(string $v):self{$this->addressType=strtoupper(trim($v));return $this;}
    public function getStreet():string{return $this->address->getStreet();} public function setStreet(string $v):self{$this->address->setStreet($v);return $this;} public function getExteriorNumber():string{return $this->address->getExteriorNumber();} public function setExteriorNumber(string $v):self{$this->address->setExteriorNumber($v);return $this;}
    public function getInteriorNumber():?string{return $this->address->getInteriorNumber();} public function setInteriorNumber(?string $v):self{$this->address->setInteriorNumber($v);return $this;} public function getNeighborhood():?string{return $this->address->getNeighborhood();} public function setNeighborhood(?string $v):self{$this->address->setNeighborhood($v);return $this;}
    public function getPostalCode():string{return $this->address->getPostalCode();} public function setPostalCode(string $v):self{$this->address->setPostalCode($v);return $this;} public function getMunicipality():string{return $this->address->getCity();} public function setMunicipality(string $v):self{$this->address->setCity($v);return $this;}
    public function getState():string{return $this->address->getState()??'';} public function setState(string $v):self{$this->address->setState($v);return $this;} public function getCountryCode():string{return $this->address->getCountryCode();} public function getReferences():?string{return $this->address->getNotes();} public function setReferences(?string $v):self{$this->address->setNotes($v);return $this;}
    public function getDeliveryZone():?DeliveryZone{return $this->deliveryZone;} public function setDeliveryZone(?DeliveryZone $v):self{$this->deliveryZone=$v;return $this;} public function getDeliveryCost():string{return $this->deliveryCost;} public function setDeliveryCost(string $v):self{$this->deliveryCost=number_format((float)str_replace(',','.',trim($v)),2,'.','');return $this;}
    public function isFiscalAddress():bool{return $this->addressType==='FISCAL';} public function setIsFiscalAddress(bool $v):self{if($v){$this->addressType='FISCAL';}elseif($this->addressType==='FISCAL'){$this->addressType='COMMERCIAL';}return $this;} public function isDeliveryAddress():bool{return $this->addressType==='DELIVERY';} public function setIsDeliveryAddress(bool $v):self{if($v){$this->addressType='DELIVERY';}elseif($this->addressType==='DELIVERY'){$this->addressType='COMMERCIAL';}return $this;}
    public function isDefaultFiscal():bool{return $this->addressType==='FISCAL'&&$this->isDefault;} public function setIsDefaultFiscal(bool $v):self{if($v){$this->addressType='FISCAL';$this->isDefault=true;}elseif($this->addressType==='FISCAL'){$this->isDefault=false;}return $this;} public function isDefaultDelivery():bool{return $this->addressType==='DELIVERY'&&$this->isDefault;} public function setIsDefaultDelivery(bool $v):self{if($v){$this->addressType='DELIVERY';$this->isDefault=true;}elseif($this->addressType==='DELIVERY'){$this->isDefault=false;}return $this;}
    public function isActive():bool{return $this->isActive;} public function setIsActive(bool $v):self{$this->isActive=$v;if(!$v){$this->isDefault=false;}return $this;} #[ORM\PreUpdate] public function updateTimestamp():void{$this->updatedAt=new \DateTimeImmutable('now',new \DateTimeZone('UTC'));}
}
