<?php
declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\AbstractMySQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260815183000 extends AbstractMigration
{
    public function getDescription(): string { return 'Normaliza domicilios, teléfonos, contactos, sucursales y datos fiscales de clientes y proveedores.'; }
    public function isTransactional(): bool { return false; }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof AbstractMySQLPlatform, 'Solo MySQL o MariaDB.');

        $this->addSql("ALTER TABLE clients ADD client_type VARCHAR(20) DEFAULT 'COMPANY' NOT NULL COMMENT 'Tipo de cliente: COMPANY o INDIVIDUAL', ADD business_activity VARCHAR(160) DEFAULT NULL COMMENT 'Giro o actividad comercial', ADD website VARCHAR(255) DEFAULT NULL COMMENT 'Sitio web', ADD birth_date DATE DEFAULT NULL COMMENT 'Cumpleaños si es persona física'");
        $this->addSql("ALTER TABLE suppliers ADD business_activity VARCHAR(160) DEFAULT NULL COMMENT 'Giro o actividad comercial', ADD website VARCHAR(255) DEFAULT NULL COMMENT 'Sitio web'");
        $this->addSql("ALTER TABLE client_categories ADD code VARCHAR(40) DEFAULT NULL COMMENT 'Código técnico estable', ADD discount_percentage NUMERIC(5,2) DEFAULT '0.00' NOT NULL COMMENT 'Porcentaje de descuento sugerido', ADD UNIQUE INDEX UNIQ_CLIENT_CATEGORY_CODE (code)");

        $this->addSql("CREATE TABLE addresses (id INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno', street VARCHAR(160) NOT NULL COMMENT 'Calle o vialidad', exterior_number VARCHAR(30) NOT NULL COMMENT 'Número exterior', interior_number VARCHAR(30) DEFAULT NULL COMMENT 'Número interior', neighborhood VARCHAR(120) DEFAULT NULL COMMENT 'Colonia', postal_code VARCHAR(10) NOT NULL COMMENT 'Código postal', city VARCHAR(120) NOT NULL COMMENT 'Ciudad o municipio', state VARCHAR(120) DEFAULT NULL COMMENT 'Estado', country_code VARCHAR(2) DEFAULT 'MX' NOT NULL COMMENT 'Código ISO del país', notes LONGTEXT DEFAULT NULL COMMENT 'Referencias o notas', created_at DATETIME NOT NULL COMMENT 'Fecha UTC de creación', updated_at DATETIME NOT NULL COMMENT 'Fecha UTC de actualización', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` COMMENT='Domicilios físicos reutilizables'");
        $this->addSql("CREATE TABLE phones (id INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno', phone_type VARCHAR(20) NOT NULL COMMENT 'LANDLINE, MOBILE, PERSONAL_MOBILE o FAX', country_code VARCHAR(5) DEFAULT '52' NOT NULL COMMENT 'Prefijo internacional', area_code VARCHAR(10) DEFAULT NULL COMMENT 'Lada', number VARCHAR(30) NOT NULL COMMENT 'Número local', extension VARCHAR(15) DEFAULT NULL COMMENT 'Extensión', notes LONGTEXT DEFAULT NULL COMMENT 'Observaciones', created_at DATETIME NOT NULL COMMENT 'Fecha UTC de creación', updated_at DATETIME NOT NULL COMMENT 'Fecha UTC de actualización', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` COMMENT='Teléfonos reutilizables'");
        $this->addSql("CREATE TABLE contacts (id INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno', first_name VARCHAR(100) NOT NULL COMMENT 'Nombre o nombres', last_name VARCHAR(120) DEFAULT NULL COMMENT 'Apellidos', personal_email VARCHAR(180) DEFAULT NULL COMMENT 'Correo personal', birth_date DATE DEFAULT NULL COMMENT 'Cumpleaños', work_days VARCHAR(100) DEFAULT NULL COMMENT 'Días habituales de atención', work_hours VARCHAR(160) DEFAULT NULL COMMENT 'Horario laboral habitual', notes LONGTEXT DEFAULT NULL COMMENT 'Observaciones', is_active TINYINT(1) DEFAULT 1 NOT NULL COMMENT 'Vigencia del contacto', created_at DATETIME NOT NULL COMMENT 'Fecha UTC de creación', updated_at DATETIME NOT NULL COMMENT 'Fecha UTC de actualización', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` COMMENT='Personas de contacto reutilizables'");

        $this->addSql("ALTER TABLE client_addresses ADD address_id INT DEFAULT NULL COMMENT 'Domicilio normalizado', ADD address_type VARCHAR(20) DEFAULT 'COMMERCIAL' NOT NULL COMMENT 'FISCAL, COMMERCIAL o DELIVERY', ADD INDEX IDX_CLIENT_ADDRESS_SHARED (address_id), ADD CONSTRAINT FK_CLIENT_ADDRESS_SHARED FOREIGN KEY (address_id) REFERENCES addresses (id)");
        $this->addSql("ALTER TABLE client_contacts ADD contact_id INT DEFAULT NULL COMMENT 'Persona normalizada', ADD client_branch_id INT DEFAULT NULL COMMENT 'Sucursal donde atiende', ADD department VARCHAR(120) DEFAULT NULL COMMENT 'Departamento', ADD can_request_products TINYINT(1) DEFAULT 1 NOT NULL COMMENT 'Puede solicitar productos'");

        $this->addSql("CREATE TABLE client_branches (id INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno', client_id INT NOT NULL COMMENT 'Cliente propietario', code VARCHAR(40) NOT NULL COMMENT 'Código único por cliente', name VARCHAR(160) NOT NULL COMMENT 'Nombre de sucursal', email VARCHAR(180) DEFAULT NULL COMMENT 'Correo general', notes LONGTEXT DEFAULT NULL COMMENT 'Observaciones', is_main TINYINT(1) DEFAULT 0 NOT NULL COMMENT 'Es casa matriz', is_active TINYINT(1) DEFAULT 1 NOT NULL COMMENT 'Vigencia', created_at DATETIME NOT NULL COMMENT 'Fecha UTC de creación', updated_at DATETIME NOT NULL COMMENT 'Fecha UTC de actualización', INDEX IDX_BRANCH_CLIENT (client_id), UNIQUE INDEX uniq_client_branch_code (client_id, code), PRIMARY KEY(id), CONSTRAINT FK_BRANCH_CLIENT FOREIGN KEY (client_id) REFERENCES clients (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` COMMENT='Sucursales de clientes'");
        $this->addSql("ALTER TABLE client_contacts ADD INDEX IDX_CLIENT_CONTACT_SHARED (contact_id), ADD INDEX IDX_CLIENT_CONTACT_BRANCH (client_branch_id), ADD CONSTRAINT FK_CLIENT_CONTACT_SHARED FOREIGN KEY (contact_id) REFERENCES contacts (id), ADD CONSTRAINT FK_CLIENT_CONTACT_BRANCH FOREIGN KEY (client_branch_id) REFERENCES client_branches (id)");

        $this->addSql("CREATE TABLE client_branch_addresses (id INT AUTO_INCREMENT NOT NULL, client_branch_id INT NOT NULL, address_id INT NOT NULL, delivery_zone_id INT DEFAULT NULL, address_type VARCHAR(20) NOT NULL, delivery_cost NUMERIC(12,2) DEFAULT NULL, is_default TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_CBA_BRANCH (client_branch_id), INDEX IDX_CBA_ADDRESS (address_id), INDEX IDX_CBA_ZONE (delivery_zone_id), UNIQUE INDEX uniq_branch_address_type (client_branch_id,address_id,address_type), PRIMARY KEY(id), CONSTRAINT FK_CBA_BRANCH FOREIGN KEY (client_branch_id) REFERENCES client_branches(id) ON DELETE CASCADE, CONSTRAINT FK_CBA_ADDRESS FOREIGN KEY(address_id) REFERENCES addresses(id), CONSTRAINT FK_CBA_ZONE FOREIGN KEY(delivery_zone_id) REFERENCES delivery_zones(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` COMMENT='Domicilios asignados a sucursales'");
        $this->addSql("CREATE TABLE supplier_addresses (id INT AUTO_INCREMENT NOT NULL, supplier_id INT NOT NULL, address_id INT NOT NULL, delivery_zone_id INT DEFAULT NULL, address_type VARCHAR(20) NOT NULL, delivery_cost NUMERIC(12,2) DEFAULT NULL, is_default TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_SA_SUPPLIER(supplier_id), INDEX IDX_SA_ADDRESS(address_id), INDEX IDX_SA_ZONE(delivery_zone_id), UNIQUE INDEX uniq_supplier_address_type(supplier_id,address_id,address_type), PRIMARY KEY(id), CONSTRAINT FK_SA_SUPPLIER FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE, CONSTRAINT FK_SA_ADDRESS FOREIGN KEY(address_id) REFERENCES addresses(id), CONSTRAINT FK_SA_ZONE FOREIGN KEY(delivery_zone_id) REFERENCES delivery_zones(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` COMMENT='Domicilios asignados a proveedores'");
        $this->addSql("CREATE TABLE contact_addresses (id INT AUTO_INCREMENT NOT NULL, contact_id INT NOT NULL, address_id INT NOT NULL, address_type VARCHAR(20) NOT NULL, is_primary TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_CA_CONTACT(contact_id), INDEX IDX_CA_ADDRESS(address_id), UNIQUE INDEX uniq_contact_address_type(contact_id,address_id,address_type), PRIMARY KEY(id), CONSTRAINT FK_CA_CONTACT FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, CONSTRAINT FK_CA_ADDRESS FOREIGN KEY(address_id) REFERENCES addresses(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` COMMENT='Domicilios personales o laborales de contactos'");

        foreach ([
            ['client_phones','client_id','clients','Cliente'], ['supplier_phones','supplier_id','suppliers','Proveedor'],
            ['client_branch_phones','client_branch_id','client_branches','Sucursal'], ['contact_phones','contact_id','contacts','Contacto'],
        ] as [$table,$ownerColumn,$ownerTable,$ownerLabel]) {
            $this->addSql("CREATE TABLE $table (id INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno', $ownerColumn INT NOT NULL COMMENT '$ownerLabel propietario', phone_id INT NOT NULL COMMENT 'Teléfono reutilizable', label VARCHAR(80) DEFAULT NULL COMMENT 'Etiqueta visible', is_primary TINYINT(1) DEFAULT 0 NOT NULL COMMENT 'Es el número principal', is_active TINYINT(1) DEFAULT 1 NOT NULL COMMENT 'Vigencia', created_at DATETIME NOT NULL COMMENT 'Fecha UTC de creación', updated_at DATETIME NOT NULL COMMENT 'Fecha UTC de actualización', INDEX IDX_{$table}_OWNER($ownerColumn), INDEX IDX_{$table}_PHONE(phone_id), UNIQUE INDEX UNIQ_{$table}_OWNER_PHONE($ownerColumn,phone_id), PRIMARY KEY(id), CONSTRAINT FK_{$table}_OWNER FOREIGN KEY($ownerColumn) REFERENCES $ownerTable(id) ON DELETE CASCADE, CONSTRAINT FK_{$table}_PHONE FOREIGN KEY(phone_id) REFERENCES phones(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` COMMENT='Asignaciones normalizadas de teléfonos'");
        }

        $this->addSql("CREATE TABLE supplier_contacts (id INT AUTO_INCREMENT NOT NULL, supplier_id INT NOT NULL COMMENT 'Proveedor', contact_id INT NOT NULL COMMENT 'Persona', department VARCHAR(120) DEFAULT NULL COMMENT 'Departamento', position VARCHAR(120) DEFAULT NULL COMMENT 'Cargo', business_email VARCHAR(180) DEFAULT NULL COMMENT 'Correo laboral', is_primary TINYINT(1) DEFAULT 0 NOT NULL COMMENT 'Contacto principal', can_sell_products TINYINT(1) DEFAULT 1 NOT NULL COMMENT 'Puede ofrecer productos', notes LONGTEXT DEFAULT NULL COMMENT 'Observaciones', is_active TINYINT(1) DEFAULT 1 NOT NULL COMMENT 'Vigencia', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_SC_SUPPLIER(supplier_id), INDEX IDX_SC_CONTACT(contact_id), UNIQUE INDEX uniq_supplier_contact(supplier_id,contact_id), PRIMARY KEY(id), CONSTRAINT FK_SC_SUPPLIER FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE, CONSTRAINT FK_SC_CONTACT FOREIGN KEY(contact_id) REFERENCES contacts(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` COMMENT='Contactos laborales de proveedores'");
        $this->addSql("CREATE TABLE tax_data (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, supplier_id INT DEFAULT NULL, fiscal_address_id INT NOT NULL, tax_regime_code VARCHAR(3) NOT NULL, billing_email VARCHAR(180) NOT NULL, cfdi_use_code VARCHAR(10) NOT NULL, is_default TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_TAX_CLIENT(client_id), INDEX IDX_TAX_SUPPLIER(supplier_id), INDEX IDX_TAX_ADDRESS(fiscal_address_id), PRIMARY KEY(id), CONSTRAINT FK_TAX_CLIENT FOREIGN KEY(client_id) REFERENCES clients(id) ON DELETE CASCADE, CONSTRAINT FK_TAX_SUPPLIER FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE, CONSTRAINT FK_TAX_ADDRESS FOREIGN KEY(fiscal_address_id) REFERENCES addresses(id), CONSTRAINT CHK_TAX_ONE_OWNER CHECK ((client_id IS NULL) <> (supplier_id IS NULL))) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` COMMENT='Configuraciones fiscales sin duplicar identidad ni domicilio'");

        $this->addSql("ALTER TABLE client_branch_addresses MODIFY id INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno', MODIFY client_branch_id INT NOT NULL COMMENT 'Sucursal propietaria', MODIFY address_id INT NOT NULL COMMENT 'Domicilio reutilizable', MODIFY delivery_zone_id INT DEFAULT NULL COMMENT 'Zona de entrega', MODIFY address_type VARCHAR(20) NOT NULL COMMENT 'FISCAL, COMMERCIAL o DELIVERY', MODIFY delivery_cost NUMERIC(12,2) DEFAULT NULL COMMENT 'Costo de entrega', MODIFY is_default TINYINT(1) DEFAULT 0 NOT NULL COMMENT 'Domicilio predeterminado', MODIFY is_active TINYINT(1) DEFAULT 1 NOT NULL COMMENT 'Vigencia', MODIFY created_at DATETIME NOT NULL COMMENT 'Fecha UTC de creación', MODIFY updated_at DATETIME NOT NULL COMMENT 'Fecha UTC de actualización'");
        $this->addSql("ALTER TABLE supplier_addresses MODIFY id INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno', MODIFY supplier_id INT NOT NULL COMMENT 'Proveedor propietario', MODIFY address_id INT NOT NULL COMMENT 'Domicilio reutilizable', MODIFY delivery_zone_id INT DEFAULT NULL COMMENT 'Zona de entrega', MODIFY address_type VARCHAR(20) NOT NULL COMMENT 'FISCAL, COMMERCIAL o DELIVERY', MODIFY delivery_cost NUMERIC(12,2) DEFAULT NULL COMMENT 'Costo de entrega', MODIFY is_default TINYINT(1) DEFAULT 0 NOT NULL COMMENT 'Domicilio predeterminado', MODIFY is_active TINYINT(1) DEFAULT 1 NOT NULL COMMENT 'Vigencia', MODIFY created_at DATETIME NOT NULL COMMENT 'Fecha UTC de creación', MODIFY updated_at DATETIME NOT NULL COMMENT 'Fecha UTC de actualización'");
        $this->addSql("ALTER TABLE contact_addresses MODIFY id INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno', MODIFY contact_id INT NOT NULL COMMENT 'Persona propietaria', MODIFY address_id INT NOT NULL COMMENT 'Domicilio reutilizable', MODIFY address_type VARCHAR(20) NOT NULL COMMENT 'PERSONAL o WORK', MODIFY is_primary TINYINT(1) DEFAULT 0 NOT NULL COMMENT 'Domicilio principal', MODIFY is_active TINYINT(1) DEFAULT 1 NOT NULL COMMENT 'Vigencia', MODIFY created_at DATETIME NOT NULL COMMENT 'Fecha UTC de creación', MODIFY updated_at DATETIME NOT NULL COMMENT 'Fecha UTC de actualización'");
        $this->addSql("ALTER TABLE supplier_contacts MODIFY id INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno', MODIFY created_at DATETIME NOT NULL COMMENT 'Fecha UTC de creación', MODIFY updated_at DATETIME NOT NULL COMMENT 'Fecha UTC de actualización'");
        $this->addSql("ALTER TABLE tax_data MODIFY id INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno', MODIFY client_id INT DEFAULT NULL COMMENT 'Cliente propietario', MODIFY supplier_id INT DEFAULT NULL COMMENT 'Proveedor propietario', MODIFY fiscal_address_id INT NOT NULL COMMENT 'Domicilio fiscal reutilizable', MODIFY tax_regime_code VARCHAR(3) NOT NULL COMMENT 'Clave SAT de régimen fiscal', MODIFY billing_email VARCHAR(180) NOT NULL COMMENT 'Correo de facturación', MODIFY cfdi_use_code VARCHAR(10) NOT NULL COMMENT 'Uso CFDI predeterminado', MODIFY is_default TINYINT(1) DEFAULT 0 NOT NULL COMMENT 'Configuración predeterminada', MODIFY is_active TINYINT(1) DEFAULT 1 NOT NULL COMMENT 'Vigencia', MODIFY created_at DATETIME NOT NULL COMMENT 'Fecha UTC de creación', MODIFY updated_at DATETIME NOT NULL COMMENT 'Fecha UTC de actualización'");

        $this->addSql("INSERT INTO addresses (id,street,exterior_number,interior_number,neighborhood,postal_code,city,state,country_code,notes,created_at,updated_at) SELECT id,street,exterior_number,interior_number,neighborhood,postal_code,municipality,state,country_code,references_text,created_at,updated_at FROM client_addresses");
        $this->addSql("UPDATE client_addresses SET address_id=id, address_type=CASE WHEN is_delivery_address=1 THEN 'DELIVERY' WHEN is_fiscal_address=1 THEN 'FISCAL' ELSE 'COMMERCIAL' END");
        $this->addSql("INSERT INTO contacts (id,first_name,last_name,personal_email,work_hours,is_active,created_at,updated_at) SELECT id,TRIM(SUBSTRING_INDEX(full_name,' ',1)),NULLIF(TRIM(SUBSTRING(full_name,LENGTH(SUBSTRING_INDEX(full_name,' ',1))+1)),''),email,work_schedule,is_active,created_at,updated_at FROM client_contacts");
        $this->addSql("UPDATE client_contacts SET contact_id=id");
        $this->addSql("INSERT INTO tax_data (client_id,fiscal_address_id,tax_regime_code,billing_email,cfdi_use_code,is_default,is_active,created_at,updated_at) SELECT c.id,ca.address_id,c.tax_regime_code,c.billing_email,c.default_cfdi_use_code,1,1,c.created_at,c.updated_at FROM clients c INNER JOIN client_addresses ca ON ca.client_id=c.id AND ca.is_active=1 AND ca.is_fiscal_address=1 AND ca.is_default_fiscal=1 WHERE c.tax_regime_code IS NOT NULL AND c.billing_email IS NOT NULL AND c.default_cfdi_use_code IS NOT NULL");
        $this->addSql("INSERT INTO phones (id,phone_type,number,created_at,updated_at) SELECT id,'LANDLINE',phone,created_at,updated_at FROM clients WHERE phone IS NOT NULL AND phone<>''");
        $this->addSql("INSERT INTO client_phones (client_id,phone_id,label,is_primary,is_active,created_at,updated_at) SELECT id,id,'General',1,is_active,created_at,updated_at FROM clients WHERE phone IS NOT NULL AND phone<>''");
        $this->addSql("INSERT INTO phones (id,phone_type,number,created_at,updated_at) SELECT 100000000+id,'LANDLINE',phone,created_at,updated_at FROM suppliers WHERE phone IS NOT NULL AND phone<>''");
        $this->addSql("INSERT INTO supplier_phones (supplier_id,phone_id,label,is_primary,is_active,created_at,updated_at) SELECT id,100000000+id,'General',1,is_active,created_at,updated_at FROM suppliers WHERE phone IS NOT NULL AND phone<>''");
        $this->addSql('ALTER TABLE addresses AUTO_INCREMENT=200000000');
        $this->addSql('ALTER TABLE contacts AUTO_INCREMENT=200000000');
        $this->addSql('ALTER TABLE phones AUTO_INCREMENT=200000000');
    }

    public function down(Schema $schema): void
    {
        foreach (['tax_data','supplier_contacts','contact_phones','client_branch_phones','supplier_phones','client_phones','contact_addresses','supplier_addresses','client_branch_addresses'] as $table) { $this->addSql("DROP TABLE $table"); }
        $this->addSql('ALTER TABLE client_contacts DROP FOREIGN KEY FK_CLIENT_CONTACT_BRANCH, DROP FOREIGN KEY FK_CLIENT_CONTACT_SHARED, DROP client_branch_id, DROP contact_id, DROP department, DROP can_request_products');
        $this->addSql('DROP TABLE client_branches');
        $this->addSql('ALTER TABLE client_addresses DROP FOREIGN KEY FK_CLIENT_ADDRESS_SHARED, DROP address_id, DROP address_type');
        $this->addSql('DROP TABLE contacts'); $this->addSql('DROP TABLE phones'); $this->addSql('DROP TABLE addresses');
        $this->addSql('ALTER TABLE client_categories DROP INDEX UNIQ_CLIENT_CATEGORY_CODE, DROP code, DROP discount_percentage');
        $this->addSql('ALTER TABLE suppliers DROP business_activity, DROP website');
        $this->addSql('ALTER TABLE clients DROP client_type, DROP business_activity, DROP website, DROP birth_date');
    }
}
