<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Platforms\AbstractMySQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260815180000 extends AbstractMigration
{
 public function getDescription():string{return 'Modelo incremental de variantes, BOM, costos MXN, lotes, movimientos y consumo de producción.';}
 public function isTransactional(): bool { return false; }
 public function up(Schema $schema):void
 {
  $this->abortIf(!$this->connection->getDatabasePlatform() instanceof AbstractMySQLPlatform,'Solo MySQL/MariaDB.');
  $schemaManager=$this->connection->createSchemaManager();
  if(!$schemaManager->introspectTable('measurement_units')->hasColumn('base_unit_id')) {
   $this->addSql("ALTER TABLE measurement_units ADD base_unit_id INT DEFAULT NULL, ADD symbol VARCHAR(20) NOT NULL DEFAULT '', ADD dimension_type VARCHAR(20) NOT NULL DEFAULT 'COUNT', ADD conversion_factor NUMERIC(24,12) NOT NULL DEFAULT 1, ADD decimal_scale SMALLINT UNSIGNED NOT NULL DEFAULT 6, ADD allows_fraction TINYINT(1) NOT NULL DEFAULT 1, ADD CONSTRAINT fk_units_base FOREIGN KEY(base_unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, ADD CONSTRAINT chk_units_dimension CHECK(dimension_type IN ('COUNT','LENGTH','AREA','VOLUME','MASS','TIME')), ADD CONSTRAINT chk_units_factor CHECK(conversion_factor>0)");
  }
  $this->addSql("UPDATE measurement_units SET symbol=CASE code WHEN 'PZA' THEN 'pza' WHEN 'ROLLO' THEN 'rollo' WHEN 'M' THEN 'm' WHEN 'ML' THEN 'ml' WHEN 'M2' THEN 'm²' WHEN 'CM' THEN 'cm' WHEN 'MM' THEN 'mm' WHEN 'L' THEN 'L' WHEN 'KG' THEN 'kg' WHEN 'G' THEN 'g' ELSE code END, dimension_type=CASE WHEN code IN('M','ML','CM','MM') THEN 'LENGTH' WHEN code='M2' THEN 'AREA' WHEN code IN('L','ML_VOL') THEN 'VOLUME' WHEN code IN('KG','G') THEN 'MASS' WHEN code IN('MIN','H') THEN 'TIME' ELSE 'COUNT' END, conversion_factor=CASE code WHEN 'CM' THEN 0.01 WHEN 'MM' THEN 0.001 WHEN 'ML_VOL' THEN 0.001 WHEN 'G' THEN 0.001 WHEN 'H' THEN 60 ELSE 1 END");
  if(!$schemaManager->introspectTable('material_categories')->hasColumn('parent_id')) {
   $this->addSql("ALTER TABLE material_categories ADD parent_id INT DEFAULT NULL, ADD category_type VARCHAR(24) NOT NULL DEFAULT 'CONSUMABLE', ADD inventory_controlled TINYINT(1) NOT NULL DEFAULT 1, ADD CONSTRAINT fk_material_categories_parent FOREIGN KEY(parent_id) REFERENCES material_categories(id) ON DELETE RESTRICT");
  }
  $this->addSql("CREATE TRIGGER trg_material_categories_no_cycle BEFORE UPDATE ON material_categories FOR EACH ROW BEGIN DECLARE cursor_id INT; DECLARE depth_count INT DEFAULT 0; SET cursor_id=NEW.parent_id; WHILE cursor_id IS NOT NULL DO IF cursor_id=NEW.id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Material category cycle'; END IF; SELECT parent_id INTO cursor_id FROM material_categories WHERE id=cursor_id; SET depth_count=depth_count+1; IF depth_count>100 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Material category hierarchy too deep'; END IF; END WHILE; END");
  if(!$schemaManager->introspectTable('materials')->hasColumn('default_inventory_unit_id')) {
   $this->addSql("ALTER TABLE materials ADD default_inventory_unit_id INT DEFAULT NULL, ADD default_consumption_unit_id INT DEFAULT NULL, ADD material_type VARCHAR(30) NOT NULL DEFAULT 'CONSUMABLE', ADD is_stock_item TINYINT(1) NOT NULL DEFAULT 1, ADD is_purchasable TINYINT(1) NOT NULL DEFAULT 1, ADD is_consumable TINYINT(1) NOT NULL DEFAULT 1, ADD is_hazardous TINYINT(1) NOT NULL DEFAULT 0, ADD requires_lot_control TINYINT(1) NOT NULL DEFAULT 0, ADD requires_expiration_control TINYINT(1) NOT NULL DEFAULT 0, ADD default_waste_percentage NUMERIC(7,4) NOT NULL DEFAULT 0, ADD storage_conditions LONGTEXT DEFAULT NULL, ADD technical_notes LONGTEXT DEFAULT NULL, ADD CONSTRAINT fk_materials_default_inventory_unit FOREIGN KEY(default_inventory_unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, ADD CONSTRAINT fk_materials_default_consumption_unit FOREIGN KEY(default_consumption_unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, ADD CONSTRAINT chk_materials_waste CHECK(default_waste_percentage BETWEEN 0 AND 100)");
  }
  $this->addSql('UPDATE materials SET default_inventory_unit_id=measurement_unit_id, default_consumption_unit_id=measurement_unit_id WHERE default_inventory_unit_id IS NULL');
  foreach(['brands'=>'120','manufacturers'=>'160','colors'=>'100','finishes'=>'100','adhesive_types'=>'100'] as $table=>$length){$extra=$table==='colors'?', hex_value VARCHAR(7) DEFAULT NULL':'';$this->addSql("CREATE TABLE $table (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(40) NOT NULL, name VARCHAR($length) NOT NULL$extra, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX uniq_{$table}_code(code), UNIQUE INDEX uniq_{$table}_name(name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");}
  $this->addSql("CREATE TABLE material_variants (id INT AUTO_INCREMENT NOT NULL, material_id INT NOT NULL, brand_id INT DEFAULT NULL, color_id INT DEFAULT NULL, finish_id INT DEFAULT NULL, adhesive_type_id INT DEFAULT NULL, purchase_unit_id INT NOT NULL, inventory_unit_id INT NOT NULL, consumption_unit_id INT NOT NULL, code VARCHAR(80) NOT NULL, manufacturer_sku VARCHAR(100) DEFAULT NULL, barcode VARCHAR(80) DEFAULT NULL, specifications JSON NOT NULL, purchase_to_inventory_factor NUMERIC(24,12) NOT NULL DEFAULT 1, inventory_to_consumption_factor NUMERIC(24,12) NOT NULL DEFAULT 1, reference_cost_mxn NUMERIC(19,6) DEFAULT NULL, minimum_stock NUMERIC(20,6) NOT NULL DEFAULT 0, reorder_point NUMERIC(20,6) NOT NULL DEFAULT 0, reorder_quantity NUMERIC(20,6) NOT NULL DEFAULT 0, lot_controlled TINYINT(1) NOT NULL DEFAULT 0, expiration_controlled TINYINT(1) NOT NULL DEFAULT 0, is_default TINYINT(1) NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, default_material_key INT GENERATED ALWAYS AS (CASE WHEN is_default=1 AND is_active=1 THEN material_id ELSE NULL END) STORED, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX uniq_material_variants_code(code), UNIQUE INDEX uniq_material_variants_barcode(barcode), UNIQUE INDEX uniq_material_variants_default(default_material_key), INDEX idx_variants_material_active(material_id,is_active), PRIMARY KEY(id), FOREIGN KEY(material_id) REFERENCES materials(id) ON DELETE RESTRICT, FOREIGN KEY(brand_id) REFERENCES brands(id) ON DELETE RESTRICT, FOREIGN KEY(color_id) REFERENCES colors(id) ON DELETE RESTRICT, FOREIGN KEY(finish_id) REFERENCES finishes(id) ON DELETE RESTRICT, FOREIGN KEY(adhesive_type_id) REFERENCES adhesive_types(id) ON DELETE RESTRICT, FOREIGN KEY(purchase_unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, FOREIGN KEY(inventory_unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, FOREIGN KEY(consumption_unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, CHECK(purchase_to_inventory_factor>0 AND inventory_to_consumption_factor>0), CHECK(reference_cost_mxn IS NULL OR reference_cost_mxn>=0)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
  $this->addSql("INSERT INTO material_variants(material_id,purchase_unit_id,inventory_unit_id,consumption_unit_id,code,specifications,reference_cost_mxn,minimum_stock,lot_controlled,expiration_controlled,is_default,is_active,created_at,updated_at) SELECT id,measurement_unit_id,measurement_unit_id,measurement_unit_id,CONCAT(code,'-DEFAULT'),JSON_OBJECT('legacy_migration',TRUE),reference_cost,minimum_stock,0,0,1,is_active,created_at,updated_at FROM materials");
  $this->addSql("CREATE TABLE material_variant_conversions (id INT AUTO_INCREMENT NOT NULL, material_variant_id INT NOT NULL, from_unit_id INT NOT NULL, to_unit_id INT NOT NULL, factor NUMERIC(24,12) NOT NULL, is_bidirectional TINYINT(1) NOT NULL DEFAULT 1, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX uniq_material_variant_conversion(material_variant_id,from_unit_id,to_unit_id), PRIMARY KEY(id), FOREIGN KEY(material_variant_id) REFERENCES material_variants(id) ON DELETE CASCADE, FOREIGN KEY(from_unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, FOREIGN KEY(to_unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, CHECK(from_unit_id<>to_unit_id AND factor>0)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
  $this->addSql("CREATE TABLE supplier_material_variants (id INT AUTO_INCREMENT NOT NULL, supplier_id INT NOT NULL, material_variant_id INT NOT NULL, purchase_unit_id INT NOT NULL, supplier_sku VARCHAR(100) DEFAULT NULL, unit_cost_mxn NUMERIC(19,6) NOT NULL, valid_from DATETIME NOT NULL, valid_until DATETIME DEFAULT NULL, is_preferred TINYINT(1) NOT NULL DEFAULT 0, priority INT NOT NULL DEFAULT 100, is_active TINYINT(1) NOT NULL DEFAULT 1, preferred_variant_key INT GENERATED ALWAYS AS (CASE WHEN is_preferred=1 AND is_active=1 THEN material_variant_id ELSE NULL END) STORED, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX uniq_supplier_material_variant(supplier_id,material_variant_id), UNIQUE INDEX uniq_supplier_sku(supplier_id,supplier_sku), UNIQUE INDEX uniq_preferred_supplier_variant(preferred_variant_key), PRIMARY KEY(id), FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT, FOREIGN KEY(material_variant_id) REFERENCES material_variants(id) ON DELETE RESTRICT, FOREIGN KEY(purchase_unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, CHECK(unit_cost_mxn>=0), CHECK(valid_until IS NULL OR valid_until>valid_from)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
  $this->addSql("CREATE TABLE product_categories (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, code VARCHAR(40) NOT NULL, name VARCHAR(120) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX uniq_product_categories_code(code), PRIMARY KEY(id), FOREIGN KEY(parent_id) REFERENCES product_categories(id) ON DELETE RESTRICT) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
  $this->addSql("CREATE TRIGGER trg_product_categories_no_cycle BEFORE UPDATE ON product_categories FOR EACH ROW BEGIN DECLARE cursor_id INT; DECLARE depth_count INT DEFAULT 0; SET cursor_id=NEW.parent_id; WHILE cursor_id IS NOT NULL DO IF cursor_id=NEW.id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Product category cycle'; END IF; SELECT parent_id INTO cursor_id FROM product_categories WHERE id=cursor_id; SET depth_count=depth_count+1; IF depth_count>100 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Product category hierarchy too deep'; END IF; END WHILE; END");
  $this->addSql("INSERT INTO product_categories(code,name,is_active,created_at,updated_at) VALUES ('BANNER_PRINT','Impresión en lona',1,UTC_TIMESTAMP(),UTC_TIMESTAMP()),('VINYL_PRINT','Impresión en vinil',1,UTC_TIMESTAMP(),UTC_TIMESTAMP()),('LABELS','Etiquetas y calcomanías',1,UTC_TIMESTAMP(),UTC_TIMESTAMP()),('SIGNWRITING','Rotulación',1,UTC_TIMESTAMP(),UTC_TIMESTAMP()),('SIGNAGE','Señalización',1,UTC_TIMESTAMP(),UTC_TIMESTAMP()),('DECORATION','Decoración',1,UTC_TIMESTAMP(),UTC_TIMESTAMP()),('AUTOMOTIVE_PROTECTION','Protección automotriz',1,UTC_TIMESTAMP(),UTC_TIMESTAMP()),('INSTALLATION_SERVICES','Servicios de instalación',1,UTC_TIMESTAMP(),UTC_TIMESTAMP())");
  $this->addSql("CREATE TABLE products (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, sale_unit_id INT NOT NULL, production_unit_id INT NOT NULL, code VARCHAR(80) NOT NULL, name VARCHAR(180) NOT NULL, description LONGTEXT DEFAULT NULL, product_type VARCHAR(20) NOT NULL, base_price_mxn NUMERIC(19,4) DEFAULT NULL, configuration_schema JSON DEFAULT NULL, requires_production TINYINT(1) NOT NULL DEFAULT 0, requires_installation TINYINT(1) NOT NULL DEFAULT 0, is_stock_item TINYINT(1) NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX uniq_products_code(code), PRIMARY KEY(id), FOREIGN KEY(category_id) REFERENCES product_categories(id) ON DELETE RESTRICT, FOREIGN KEY(sale_unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, FOREIGN KEY(production_unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, CHECK(product_type IN('MANUFACTURED','RESALE','SERVICE','CONFIGURABLE')), CHECK(base_price_mxn IS NULL OR base_price_mxn>=0)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
  $this->addSql("CREATE TABLE bill_of_material_items (id INT AUTO_INCREMENT NOT NULL, product_id INT NOT NULL, material_id INT DEFAULT NULL, material_variant_id INT DEFAULT NULL, measurement_unit_id INT NOT NULL, quantity NUMERIC(20,6) NOT NULL, waste_percentage NUMERIC(7,4) NOT NULL DEFAULT 0, calculation_method VARCHAR(30) NOT NULL, calculation_method_version INT NOT NULL DEFAULT 1, calculation_parameters JSON DEFAULT NULL, sequence INT NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX uniq_bom_product_sequence(product_id,sequence), PRIMARY KEY(id), FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE RESTRICT, FOREIGN KEY(material_id) REFERENCES materials(id) ON DELETE RESTRICT, FOREIGN KEY(material_variant_id) REFERENCES material_variants(id) ON DELETE RESTRICT, FOREIGN KEY(measurement_unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, CHECK((material_id IS NULL)<>(material_variant_id IS NULL)), CHECK(quantity>=0 AND waste_percentage BETWEEN 0 AND 100), CHECK(calculation_method IN('FIXED','AREA','LENGTH','PERIMETER','VOLUME','PERCENTAGE','AREA_YIELD','PERIMETER_SPACING','SHEET_LAYOUT','ROLL_LAYOUT'))) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
  $this->addSql("CREATE TABLE inventory_lots (id INT AUTO_INCREMENT NOT NULL, material_variant_id INT NOT NULL, internal_lot_number VARCHAR(100) NOT NULL, manufacturer_lot_number VARCHAR(100) DEFAULT NULL, manufactured_at DATE DEFAULT NULL, expires_at DATE DEFAULT NULL, received_unit_cost_mxn NUMERIC(19,6) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX uniq_inventory_lot_internal(internal_lot_number), PRIMARY KEY(id), FOREIGN KEY(material_variant_id) REFERENCES material_variants(id) ON DELETE RESTRICT, CHECK(expires_at IS NULL OR manufactured_at IS NULL OR expires_at>=manufactured_at)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
  $this->addSql("CREATE TABLE inventory_movements (id INT AUTO_INCREMENT NOT NULL, material_variant_id INT NOT NULL, lot_id INT DEFAULT NULL, unit_id INT NOT NULL, responsible_user_id INT NOT NULL, negative_stock_authorized_by INT DEFAULT NULL, movement_type VARCHAR(30) NOT NULL, quantity NUMERIC(20,6) NOT NULL, unit_cost_mxn NUMERIC(19,6) DEFAULT NULL, source_type VARCHAR(50) NOT NULL, source_id INT DEFAULT NULL, is_provisional_receipt TINYINT(1) NOT NULL DEFAULT 0, negative_stock_reason VARCHAR(255) DEFAULT NULL, occurred_at DATETIME NOT NULL, created_at DATETIME NOT NULL, INDEX idx_inventory_stock(material_variant_id,occurred_at), INDEX idx_inventory_lot(lot_id,occurred_at), PRIMARY KEY(id), FOREIGN KEY(material_variant_id) REFERENCES material_variants(id) ON DELETE RESTRICT, FOREIGN KEY(lot_id) REFERENCES inventory_lots(id) ON DELETE RESTRICT, FOREIGN KEY(unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, FOREIGN KEY(responsible_user_id) REFERENCES users(id) ON DELETE RESTRICT, FOREIGN KEY(negative_stock_authorized_by) REFERENCES users(id) ON DELETE RESTRICT, CHECK(quantity<>0), CHECK(movement_type IN('PURCHASE','RECEIPT','PRODUCTION_CONSUMPTION','SALE','RETURN','ADJUSTMENT_IN','ADJUSTMENT_OUT','WASTE','RESERVATION','RELEASE'))) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
  $this->addSql("CREATE TABLE material_variant_costs (material_variant_id INT NOT NULL, on_hand_quantity NUMERIC(20,6) NOT NULL DEFAULT 0, inventory_value_mxn NUMERIC(19,6) NOT NULL DEFAULT 0, moving_average_cost_mxn NUMERIC(19,6) NOT NULL DEFAULT 0, updated_at DATETIME NOT NULL, PRIMARY KEY(material_variant_id), FOREIGN KEY(material_variant_id) REFERENCES material_variants(id) ON DELETE RESTRICT, CHECK(on_hand_quantity>=0 AND inventory_value_mxn>=0 AND moving_average_cost_mxn>=0)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
  $this->addSql("INSERT INTO material_variant_costs(material_variant_id,on_hand_quantity,inventory_value_mxn,moving_average_cost_mxn,updated_at) SELECT id,0,0,COALESCE(reference_cost_mxn,0),UTC_TIMESTAMP() FROM material_variants");
  $this->addSql("CREATE TABLE production_material_usages (id INT AUTO_INCREMENT NOT NULL, service_order_item_id INT NOT NULL, material_variant_id INT NOT NULL, lot_id INT DEFAULT NULL, unit_id INT NOT NULL, inventory_movement_id INT DEFAULT NULL, measured_by INT DEFAULT NULL, planned_quantity NUMERIC(20,6) NOT NULL, actual_quantity NUMERIC(20,6) DEFAULT NULL, posted_quantity NUMERIC(20,6) NOT NULL, waste_quantity NUMERIC(20,6) DEFAULT NULL, quantity_source VARCHAR(20) NOT NULL, measurement_method VARCHAR(30) DEFAULT NULL, waste_reason VARCHAR(255) DEFAULT NULL, calculation_method VARCHAR(30) NOT NULL, calculation_method_version INT NOT NULL, calculation_snapshot JSON NOT NULL, measured_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX idx_usage_order_item(service_order_item_id), PRIMARY KEY(id), FOREIGN KEY(service_order_item_id) REFERENCES service_order_items(id) ON DELETE RESTRICT, FOREIGN KEY(material_variant_id) REFERENCES material_variants(id) ON DELETE RESTRICT, FOREIGN KEY(lot_id) REFERENCES inventory_lots(id) ON DELETE RESTRICT, FOREIGN KEY(unit_id) REFERENCES measurement_units(id) ON DELETE RESTRICT, FOREIGN KEY(inventory_movement_id) REFERENCES inventory_movements(id) ON DELETE RESTRICT, FOREIGN KEY(measured_by) REFERENCES users(id) ON DELETE RESTRICT, CHECK(waste_quantity IS NULL OR actual_quantity IS NOT NULL), CHECK(actual_quantity IS NULL OR waste_quantity IS NULL OR waste_quantity<=actual_quantity), CHECK(quantity_source IN('ESTIMATED','MEASURED','DERIVED','MACHINE'))) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE=InnoDB");
 }
 public function down(Schema $schema):void
 {
  $this->abortIf((int)$this->connection->fetchOne('SELECT COUNT(*) FROM inventory_movements')>0,'No se puede revertir con movimientos de inventario.');
  $this->addSql('DROP TRIGGER IF EXISTS trg_product_categories_no_cycle');
  $this->addSql('DROP TRIGGER IF EXISTS trg_material_categories_no_cycle');
  foreach(['production_material_usages','material_variant_costs','inventory_movements','inventory_lots','bill_of_material_items','products','product_categories','supplier_material_variants','material_variant_conversions','material_variants','adhesive_types','finishes','colors','manufacturers','brands'] as $table)$this->addSql("DROP TABLE $table");
  $this->addSql('ALTER TABLE materials DROP FOREIGN KEY fk_materials_default_inventory_unit, DROP FOREIGN KEY fk_materials_default_consumption_unit, DROP default_inventory_unit_id, DROP default_consumption_unit_id, DROP material_type, DROP is_stock_item, DROP is_purchasable, DROP is_consumable, DROP is_hazardous, DROP requires_lot_control, DROP requires_expiration_control, DROP default_waste_percentage, DROP storage_conditions, DROP technical_notes');
  $this->addSql('ALTER TABLE material_categories DROP FOREIGN KEY fk_material_categories_parent, DROP parent_id, DROP category_type, DROP inventory_controlled');
  $this->addSql('ALTER TABLE measurement_units DROP FOREIGN KEY fk_units_base, DROP base_unit_id, DROP symbol, DROP dimension_type, DROP conversion_factor, DROP decimal_scale, DROP allows_fraction');
 }
}
