<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Platforms\AbstractMySQLPlatform; use Doctrine\DBAL\Schema\Schema; use Doctrine\Migrations\AbstractMigration;

final class Version20260816010000 extends AbstractMigration
{
    public function getDescription():string{return 'Elimina teléfonos directos y datos físicos duplicados de domicilios después de su normalización.';}
    public function isTransactional():bool{return false;}
    public function up(Schema $schema):void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof AbstractMySQLPlatform,'Solo MySQL o MariaDB.');
        $this->addSql("UPDATE client_addresses ca INNER JOIN addresses a ON a.id=ca.address_id SET a.street=ca.street,a.exterior_number=ca.exterior_number,a.interior_number=ca.interior_number,a.neighborhood=ca.neighborhood,a.postal_code=ca.postal_code,a.city=ca.municipality,a.state=ca.state,a.country_code=ca.country_code,a.notes=ca.references_text,a.updated_at=ca.updated_at");
        $this->addSql("INSERT INTO phones (id,phone_type,country_code,number,created_at,updated_at) SELECT 500000000+c.id,'LANDLINE','52',c.phone,c.created_at,c.updated_at FROM clients c LEFT JOIN client_phones cp ON cp.client_id=c.id AND cp.is_primary=1 AND cp.is_active=1 WHERE c.phone IS NOT NULL AND c.phone<>'' AND cp.id IS NULL");
        $this->addSql("INSERT INTO client_phones (client_id,phone_id,label,is_primary,is_active,created_at,updated_at) SELECT c.id,500000000+c.id,'General',1,1,c.created_at,c.updated_at FROM clients c LEFT JOIN client_phones cp ON cp.client_id=c.id AND cp.is_primary=1 WHERE c.phone IS NOT NULL AND c.phone<>'' AND cp.id IS NULL");
        $this->addSql("INSERT INTO phones (id,phone_type,country_code,number,created_at,updated_at) SELECT 600000000+s.id,'LANDLINE','52',s.phone,s.created_at,s.updated_at FROM suppliers s LEFT JOIN supplier_phones sp ON sp.supplier_id=s.id AND sp.is_primary=1 AND sp.is_active=1 WHERE s.phone IS NOT NULL AND s.phone<>'' AND sp.id IS NULL");
        $this->addSql("INSERT INTO supplier_phones (supplier_id,phone_id,label,is_primary,is_active,created_at,updated_at) SELECT s.id,600000000+s.id,'General',1,1,s.created_at,s.updated_at FROM suppliers s LEFT JOIN supplier_phones sp ON sp.supplier_id=s.id AND sp.is_primary=1 WHERE s.phone IS NOT NULL AND s.phone<>'' AND sp.id IS NULL");
        $this->addSql("UPDATE contacts p INNER JOIN client_contacts cc ON cc.contact_id=p.id SET p.work_hours=COALESCE(cc.work_schedule,p.work_hours),p.updated_at=cc.updated_at");
        $this->addSql("INSERT INTO phones (id,phone_type,country_code,number,extension,created_at,updated_at) SELECT 700000000+cc.id,'LANDLINE','52',cc.phone,cc.phone_extension,cc.created_at,cc.updated_at FROM client_contacts cc LEFT JOIN contact_phones cp ON cp.contact_id=cc.contact_id AND cp.is_primary=1 WHERE cc.phone IS NOT NULL AND cc.phone<>'' AND cp.id IS NULL");
        $this->addSql("INSERT INTO contact_phones (contact_id,phone_id,label,is_primary,is_active,created_at,updated_at) SELECT cc.contact_id,700000000+cc.id,'Principal',1,cc.is_active,cc.created_at,cc.updated_at FROM client_contacts cc LEFT JOIN contact_phones cp ON cp.contact_id=cc.contact_id AND cp.is_primary=1 WHERE cc.phone IS NOT NULL AND cc.phone<>'' AND cp.id IS NULL");
        $this->addSql("INSERT INTO phones (id,phone_type,country_code,number,created_at,updated_at) SELECT 710000000+cc.id,'MOBILE','52',cc.mobile_phone,cc.created_at,cc.updated_at FROM client_contacts cc WHERE cc.mobile_phone IS NOT NULL AND cc.mobile_phone<>''");
        $this->addSql("INSERT INTO contact_phones (contact_id,phone_id,label,is_primary,is_active,created_at,updated_at) SELECT cc.contact_id,710000000+cc.id,'Celular',0,cc.is_active,cc.created_at,cc.updated_at FROM client_contacts cc WHERE cc.mobile_phone IS NOT NULL AND cc.mobile_phone<>''");
        $this->addSql("INSERT INTO phones (id,phone_type,country_code,number,created_at,updated_at) SELECT 720000000+cc.id,'PERSONAL_MOBILE','52',cc.personal_mobile_phone,cc.created_at,cc.updated_at FROM client_contacts cc WHERE cc.personal_mobile_phone IS NOT NULL AND cc.personal_mobile_phone<>''");
        $this->addSql("INSERT INTO contact_phones (contact_id,phone_id,label,is_primary,is_active,created_at,updated_at) SELECT cc.contact_id,720000000+cc.id,'Celular personal',0,cc.is_active,cc.created_at,cc.updated_at FROM client_contacts cc WHERE cc.personal_mobile_phone IS NOT NULL AND cc.personal_mobile_phone<>''");
        $this->addSql("ALTER TABLE client_contacts ADD business_email VARCHAR(180) DEFAULT NULL COMMENT 'Correo laboral de la relación'");
        $this->addSql('UPDATE client_contacts SET business_email=email');
        $this->addSql('ALTER TABLE tax_data MODIFY fiscal_address_id INT DEFAULT NULL COMMENT \'Domicilio fiscal reutilizable\', MODIFY tax_regime_code VARCHAR(3) DEFAULT NULL COMMENT \'Clave SAT de régimen fiscal\', MODIFY billing_email VARCHAR(180) DEFAULT NULL COMMENT \'Correo de facturación\', MODIFY cfdi_use_code VARCHAR(10) DEFAULT NULL COMMENT \'Uso CFDI predeterminado\'');
        $this->addSql("INSERT INTO tax_data (client_id,fiscal_address_id,tax_regime_code,billing_email,cfdi_use_code,is_default,is_active,created_at,updated_at) SELECT c.id,ca.address_id,c.tax_regime_code,c.billing_email,c.default_cfdi_use_code,1,1,c.created_at,c.updated_at FROM clients c LEFT JOIN client_addresses ca ON ca.client_id=c.id AND ca.is_active=1 AND ca.is_default_fiscal=1 LEFT JOIN tax_data td ON td.client_id=c.id AND td.is_default=1 WHERE td.id IS NULL AND (c.tax_regime_code IS NOT NULL OR c.billing_email IS NOT NULL OR c.default_cfdi_use_code IS NOT NULL)");
        $this->addSql("UPDATE tax_data td INNER JOIN clients c ON c.id=td.client_id SET td.tax_regime_code=COALESCE(c.tax_regime_code,td.tax_regime_code),td.billing_email=COALESCE(c.billing_email,td.billing_email),td.cfdi_use_code=COALESCE(c.default_cfdi_use_code,td.cfdi_use_code),td.updated_at=c.updated_at WHERE td.is_default=1");
        $this->addSql("ALTER TABLE client_addresses ADD is_default TINYINT(1) DEFAULT 0 NOT NULL COMMENT 'Predeterminado para su tipo', ADD default_client_type_key VARCHAR(64) GENERATED ALWAYS AS (CASE WHEN is_active=1 AND is_default=1 THEN CONCAT(client_id, ':', address_type) ELSE NULL END) STORED");
        $this->addSql("UPDATE client_addresses SET is_default=CASE WHEN address_type='FISCAL' THEN is_default_fiscal WHEN address_type='DELIVERY' THEN is_default_delivery ELSE 0 END");
        $this->addSql('ALTER TABLE client_addresses DROP INDEX uniq_client_addresses_default_fiscal, DROP INDEX uniq_client_addresses_default_delivery, ADD UNIQUE INDEX uniq_client_address_default_type (default_client_type_key)');
        $this->addSql('ALTER TABLE clients DROP phone');
        $this->addSql('ALTER TABLE clients DROP tax_regime_code, DROP fiscal_postal_code, DROP billing_email, DROP default_cfdi_use_code');
        $this->addSql('ALTER TABLE suppliers DROP phone');
        $this->addSql('ALTER TABLE client_addresses DROP street, DROP exterior_number, DROP interior_number, DROP neighborhood, DROP postal_code, DROP municipality, DROP state, DROP country_code, DROP references_text, DROP default_fiscal_client_id, DROP default_delivery_client_id, DROP is_fiscal_address, DROP is_delivery_address, DROP is_default_fiscal, DROP is_default_delivery');
        $this->addSql('ALTER TABLE client_addresses MODIFY address_id INT NOT NULL COMMENT \'Domicilio físico normalizado y única fuente de sus componentes\'');
        $this->addSql('ALTER TABLE client_contacts DROP full_name, DROP email, DROP phone, DROP phone_extension, DROP mobile_phone, DROP personal_mobile_phone, DROP work_schedule, MODIFY contact_id INT NOT NULL COMMENT \'Persona normalizada y única fuente de datos personales\'');
    }
    public function down(Schema $schema):void
    {
        $this->addSql('ALTER TABLE clients ADD phone VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE clients ADD tax_regime_code VARCHAR(3) DEFAULT NULL, ADD fiscal_postal_code VARCHAR(5) DEFAULT NULL, ADD billing_email VARCHAR(180) DEFAULT NULL, ADD default_cfdi_use_code VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE suppliers ADD phone VARCHAR(40) DEFAULT NULL');
        $this->addSql("UPDATE clients c LEFT JOIN client_phones cp ON cp.client_id=c.id AND cp.is_primary=1 AND cp.is_active=1 LEFT JOIN phones p ON p.id=cp.phone_id SET c.phone=p.number");
        $this->addSql("UPDATE clients c LEFT JOIN tax_data td ON td.client_id=c.id AND td.is_default=1 LEFT JOIN addresses a ON a.id=td.fiscal_address_id SET c.tax_regime_code=td.tax_regime_code,c.fiscal_postal_code=a.postal_code,c.billing_email=td.billing_email,c.default_cfdi_use_code=td.cfdi_use_code");
        $this->addSql("UPDATE suppliers s LEFT JOIN supplier_phones sp ON sp.supplier_id=s.id AND sp.is_primary=1 AND sp.is_active=1 LEFT JOIN phones p ON p.id=sp.phone_id SET s.phone=p.number");
        $this->addSql("ALTER TABLE client_addresses DROP INDEX uniq_client_address_default_type, DROP default_client_type_key, ADD street VARCHAR(160) DEFAULT '' NOT NULL, ADD exterior_number VARCHAR(30) DEFAULT '' NOT NULL, ADD interior_number VARCHAR(30) DEFAULT NULL, ADD neighborhood VARCHAR(120) DEFAULT NULL, ADD postal_code VARCHAR(5) DEFAULT '' NOT NULL, ADD municipality VARCHAR(120) DEFAULT '' NOT NULL, ADD state VARCHAR(120) DEFAULT '' NOT NULL, ADD country_code VARCHAR(2) DEFAULT 'MX' NOT NULL, ADD references_text LONGTEXT DEFAULT NULL, ADD is_fiscal_address TINYINT(1) DEFAULT 0 NOT NULL, ADD is_delivery_address TINYINT(1) DEFAULT 0 NOT NULL, ADD is_default_fiscal TINYINT(1) DEFAULT 0 NOT NULL, ADD is_default_delivery TINYINT(1) DEFAULT 0 NOT NULL, ADD default_fiscal_client_id INT GENERATED ALWAYS AS (CASE WHEN is_active=1 AND is_fiscal_address=1 AND is_default_fiscal=1 THEN client_id ELSE NULL END) STORED, ADD default_delivery_client_id INT GENERATED ALWAYS AS (CASE WHEN is_active=1 AND is_delivery_address=1 AND is_default_delivery=1 THEN client_id ELSE NULL END) STORED");
        $this->addSql("UPDATE client_addresses SET is_fiscal_address=(address_type='FISCAL'),is_delivery_address=(address_type='DELIVERY'),is_default_fiscal=(address_type='FISCAL' AND is_default=1),is_default_delivery=(address_type='DELIVERY' AND is_default=1)");
        $this->addSql('ALTER TABLE client_addresses DROP is_default, ADD UNIQUE INDEX uniq_client_addresses_default_fiscal(default_fiscal_client_id), ADD UNIQUE INDEX uniq_client_addresses_default_delivery(default_delivery_client_id)');
        $this->addSql('UPDATE client_addresses ca INNER JOIN addresses a ON a.id=ca.address_id SET ca.street=a.street,ca.exterior_number=a.exterior_number,ca.interior_number=a.interior_number,ca.neighborhood=a.neighborhood,ca.postal_code=a.postal_code,ca.municipality=a.city,ca.state=COALESCE(a.state,\'\'),ca.country_code=a.country_code,ca.references_text=a.notes');
        $this->addSql('ALTER TABLE client_addresses MODIFY address_id INT DEFAULT NULL');
        $this->addSql("ALTER TABLE client_contacts ADD full_name VARCHAR(160) DEFAULT '' NOT NULL, ADD email VARCHAR(180) DEFAULT NULL, ADD phone VARCHAR(40) DEFAULT NULL, ADD phone_extension VARCHAR(15) DEFAULT NULL, ADD mobile_phone VARCHAR(40) DEFAULT NULL, ADD personal_mobile_phone VARCHAR(40) DEFAULT NULL, ADD work_schedule VARCHAR(160) DEFAULT NULL");
        $this->addSql("UPDATE client_contacts cc INNER JOIN contacts p ON p.id=cc.contact_id LEFT JOIN contact_phones cp ON cp.contact_id=p.id AND cp.is_primary=1 AND cp.is_active=1 LEFT JOIN phones ph ON ph.id=cp.phone_id SET cc.full_name=TRIM(CONCAT(p.first_name,' ',COALESCE(p.last_name,''))),cc.email=cc.business_email,cc.phone=ph.number,cc.phone_extension=ph.extension,cc.work_schedule=p.work_hours");
        $this->addSql('ALTER TABLE client_contacts DROP business_email, MODIFY contact_id INT DEFAULT NULL');
    }
}
