<?php
namespace App\Entity\Quotations;
use App\Entity\Catalog\MeasurementUnit; use App\Entity\Products\Product; use App\Entity\Products\ProductCategory; use Doctrine\DBAL\Types\Types; use Doctrine\ORM\Mapping as ORM;
#[ORM\Entity,ORM\Table(name:'quote_request_items')]
class QuoteRequestItem {
 #[ORM\Id,ORM\GeneratedValue,ORM\Column] private ?int $id=null; #[ORM\ManyToOne(inversedBy:'items'),ORM\JoinColumn(nullable:false,onDelete:'CASCADE')] private ?QuoteRequest $quoteRequest=null; #[ORM\ManyToOne,ORM\JoinColumn(nullable:false,onDelete:'RESTRICT')] private ?ProductCategory $category=null; #[ORM\ManyToOne,ORM\JoinColumn(nullable:false,onDelete:'RESTRICT')] private ?Product $product=null;
 #[ORM\Column] private int $quantity=1; #[ORM\Column(type:Types::DECIMAL,precision:10,scale:2,nullable:true)] private ?string $width=null; #[ORM\Column(type:Types::DECIMAL,precision:10,scale:2,nullable:true)] private ?string $height=null; #[ORM\ManyToOne,ORM\JoinColumn(nullable:true,onDelete:'RESTRICT')] private ?MeasurementUnit $measurementUnit=null; #[ORM\Column(length:150,nullable:true)] private ?string $material=null; #[ORM\Column(length:30,nullable:true)] private ?string $printSides=null; #[ORM\Column(type:Types::JSON,nullable:true)] private ?array $finishes=null; #[ORM\Column(type:Types::JSON,nullable:true)] private ?array $characteristics=null; #[ORM\Column(length:255,nullable:true)] private ?string $attachmentPath=null; #[ORM\Column(length:255,nullable:true)] private ?string $attachmentOriginalName=null; #[ORM\Column(type:Types::TEXT,nullable:true)] private ?string $notes=null;
 public function getId():?int{return $this->id;} public function getQuoteRequest():?QuoteRequest{return $this->quoteRequest;} public function setQuoteRequest(?QuoteRequest $v):self{$this->quoteRequest=$v;return $this;} public function getCategory():?ProductCategory{return $this->category;} public function setCategory(?ProductCategory $v):self{$this->category=$v;return $this;} public function getProduct():?Product{return $this->product;} public function setProduct(?Product $v):self{$this->product=$v;return $this;} public function getQuantity():int{return $this->quantity;} public function setQuantity(int $v):self{$this->quantity=max(1,$v);return $this;} public function getWidth():?string{return $this->width;} public function setWidth(?string $v):self{$this->width=$v;return $this;} public function getHeight():?string{return $this->height;} public function setHeight(?string $v):self{$this->height=$v;return $this;}
 public function getMeasurementUnit():?MeasurementUnit{return $this->measurementUnit;} public function setMeasurementUnit(?MeasurementUnit $v):self{$this->measurementUnit=$v;return $this;} public function getMaterial():?string{return $this->material;} public function setMaterial(?string $v):self{$v=trim((string)$v);$this->material=$v?:null;return $this;} public function getPrintSides():?string{return $this->printSides;} public function setPrintSides(?string $v):self{$this->printSides=$v;return $this;} public function getFinishes():?array{return $this->finishes;} public function setFinishes(?array $v):self{$this->finishes=$v;return $this;} public function getCharacteristics():?array{return $this->characteristics;} public function setCharacteristics(?array $v):self{$this->characteristics=$v;return $this;}
 public function getAttachmentPath():?string{return $this->attachmentPath;} public function setAttachmentPath(?string $v):self{$this->attachmentPath=$v;return $this;} public function getAttachmentOriginalName():?string{return $this->attachmentOriginalName;} public function setAttachmentOriginalName(?string $v):self{$this->attachmentOriginalName=$v;return $this;} public function getNotes():?string{return $this->notes;} public function setNotes(?string $v):self{$v=trim((string)$v);$this->notes=$v?:null;return $this;}
}
