<?php
namespace App\Form;
use App\Entity\Catalog\MeasurementUnit; use App\Entity\Products\Product; use App\Entity\Products\ProductCategory; use App\Entity\Quotations\QuoteRequestItem; use Symfony\Bridge\Doctrine\Form\Type\EntityType; use Symfony\Component\Form\AbstractType; use Symfony\Component\Form\Extension\Core\Type\ChoiceType; use Symfony\Component\Form\Extension\Core\Type\FileType; use Symfony\Component\Form\Extension\Core\Type\IntegerType; use Symfony\Component\Form\Extension\Core\Type\NumberType; use Symfony\Component\Form\Extension\Core\Type\TextareaType; use Symfony\Component\Form\Extension\Core\Type\TextType; use Symfony\Component\Form\FormBuilderInterface; use Symfony\Component\OptionsResolver\OptionsResolver;
final class QuoteRequestItemType extends AbstractType {
 public function buildForm(FormBuilderInterface $b,array $o):void{$b
  ->add('category',EntityType::class,['class'=>ProductCategory::class,'choice_label'=>'name','placeholder'=>'Busca una categoría','query_builder'=>fn($r)=>$r->createQueryBuilder('c')->where('c.isActive = true')->orderBy('c.name','ASC'),'attr'=>['class'=>'form-select pf-select2','data-action'=>'change->ui--public-quote#categoryChanged']])
  ->add('product',EntityType::class,['class'=>Product::class,'choice_label'=>'name','placeholder'=>'Selecciona un producto','query_builder'=>fn($r)=>$r->createQueryBuilder('p')->join('p.category','c')->where('p.isActive = true')->orderBy('p.name','ASC'),'choice_attr'=>fn(Product $p)=>['data-category'=>(string)$p->getCategory()->getId(),'data-schema'=>json_encode($p->getConfigurationSchema()??[],JSON_THROW_ON_ERROR)],'attr'=>['class'=>'form-select pf-select2','data-action'=>'change->ui--public-quote#productChanged']])
  ->add('quantity',IntegerType::class,['label'=>'Cantidad','attr'=>['min'=>1]])
  ->add('width',NumberType::class,['label'=>'Ancho','required'=>false,'scale'=>2,'attr'=>['min'=>'0.01','step'=>'0.01']])->add('height',NumberType::class,['label'=>'Alto','required'=>false,'scale'=>2,'attr'=>['min'=>'0.01','step'=>'0.01']])
  ->add('measurementUnit',EntityType::class,['class'=>MeasurementUnit::class,'choice_label'=>fn(MeasurementUnit $u)=>$u->getName(),'placeholder'=>'Unidad','required'=>false,'query_builder'=>fn($r)=>$r->createQueryBuilder('u')->where('u.isActive = true')->orderBy('u.displayOrder','ASC')->addOrderBy('u.name','ASC')])
  ->add('material',TextType::class,['required'=>false])->add('printSides',ChoiceType::class,['label'=>'Caras de impresión','required'=>false,'placeholder'=>'Selecciona','choices'=>['Una cara'=>'one_side','Dos caras'=>'two_sides','Por definir'=>'undefined']])
  ->add('finishes',ChoiceType::class,['required'=>false,'multiple'=>true,'expanded'=>true,'choices'=>['Laminado'=>'laminated','Corte especial'=>'special_cut','Doblado'=>'folded','Barniz'=>'varnish','Ojillos'=>'eyelets']])
  ->add('characteristicsJson',\Symfony\Component\Form\Extension\Core\Type\HiddenType::class,['mapped'=>false,'required'=>false])
  ->add('attachment',FileType::class,['mapped'=>false,'required'=>false,'label'=>'Archivo','constraints'=>[new \Symfony\Component\Validator\Constraints\File(maxSize:'20M',extensions:['pdf','ai','eps','svg','jpg','jpeg','png','tif','tiff','zip'])],'attr'=>['accept'=>'.pdf,.ai,.eps,.svg,.jpg,.jpeg,.png,.tif,.tiff,.zip']])
  ->add('notes',TextareaType::class,['required'=>false,'label'=>'Indicaciones adicionales','attr'=>['rows'=>3]]);}
 public function configureOptions(OptionsResolver $r):void{$r->setDefaults(['data_class'=>QuoteRequestItem::class]);}
}
